language: python
dist: bionic
python:
  - 3.7
install:
  - python3 -m pip install online-judge-tools
  - curl -L https://github.com/crystal-lang/crystal/releases/download/0.20.5/crystal-0.20.5-1-linux-x86_64.tar.gz | tar -xz -C /tmp
script:
  - /tmp/crystal-0.20.5-1/bin/crystal run test.cr
  - bash .vscode/test-all.sh
cache:
  directories:
    - tests