language: cpp
dist: bionic
install:
  - python3 -m pip install online-judge-tools
  - curl -L https://github.com/crystal-lang/crystal/releases/download/0.20.5/crystal-0.20.5-1-linux-x86_64.tar.gz | tar -xz -C /usr/local/share
test: .vscode/test-all.sh