require "./library/PriorityQueue.test.cr"
require "./library/SegmentTree.test.cr"
require "./library/RedBlackTree.test.cr"
require "./library/UnionFindTree.test.cr"
require "./library/ModNum.test.cr"